#ifndef PROTECTED_H
#define PROTECTED_H

typedef enum 
{
    DEFAULT,
    DIAGNOSTIC,
    DEVICE_CONTROL,
} SESSION_LEVEL;

SESSION_LEVEL CURRENT_SESSION;
int ACCESS_LEVEL;
int MEM_READ_ADDRESS;
int MEM_READ_LENGTH;
char SEED[5];
char KEY[5];
int KEY_ATTEMPTS;
int PROGRAMMING_MODE_ENABLED;
int DOWNLOAD_SIZE;
int DOWNLOAD_ADDR;
int DATA_READ_BYTES;
int SHOULD_EXEC;

char DID[0x5][0x20];

#endif